services:
  - type: web
    name: student-management
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: student-management.onrender.com
      - key: SECRET_KEY
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
