# Generated by Django 5.2.8 on 2026-03-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_examschedule_feestructure_room_admissionapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='seat_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
