# Generated by Django 5.2.8 on 2026-03-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_student_parent_name_student_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
