# Generated by Django 5.2.8 on 2026-03-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_student_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text='e.g. SEM-1', max_length=20)),
                ('exam_session', models.CharField(help_text='e.g. 2026-27', max_length=20)),
                ('declaration_accepted', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_form_submissions', to='Students.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'semester', 'exam_session')},
            },
        ),
    ]
