# Generated by Django 5.2.8 on 2026-03-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0006_examformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='examformsubmission',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='examformsubmission',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='examformsubmission',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='examformsubmission',
            name='medium',
            field=models.CharField(default='English', max_length=30),
        ),
        migrations.AddField(
            model_name='examformsubmission',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
