# Generated by Django 5.2.8 on 2026-03-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0007_examformsubmission_manual_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='examformsubmission',
            name='selected_subject_codes',
            field=models.TextField(blank=True, help_text='Comma-separated subject codes selected in exam form'),
        ),
    ]
