# Generated by Django 5.2.8 on 2026-03-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0008_examformsubmission_selected_subject_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('course', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['course', 'code'],
                'unique_together': {('course', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ExamFormSubjectSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=True)),
                ('component_internal', models.BooleanField(default=False)),
                ('component_theory', models.BooleanField(default=True)),
                ('component_online', models.BooleanField(default=False)),
                ('component_practical', models.BooleanField(default=False)),
                ('component_oral', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_selections', to='Students.examformsubmission')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_form_selections', to='Students.subject')),
            ],
            options={
                'ordering': ['subject__code'],
                'unique_together': {('submission', 'subject')},
            },
        ),
    ]
